# Este arquivo configura o analisador, que analisa estaticamente o código Dart para
# verificar erros, avisos e lints.
#
# Os problemas identificados pelo analisador são exibidos na interface do usuário de
# IDEs habilitadas para Dart (https://dart.dev/tools#ides-and-editors). O analisador também pode ser
# invocado a partir da linha de comando executando `flutter analyze`.

# A linha a seguir ativa um conjunto de lints recomendados para aplicativos Flutter,
# pacotes e plugins, projetados para encorajar boas práticas de codificação.
include: package:flutter_lints/flutter.yaml

linter:
  # As regras de lint aplicadas a este projeto podem ser personalizadas na
  # seção abaixo para desabilitar regras do `package:flutter_lints/flutter.yaml`
  # incluído acima ou para ativar regras adicionais. Uma lista de todos os lints disponíveis
  # e sua documentação está publicada em https://dart.dev/lints.
  #
  # Em vez de desabilitar uma regra de lint para todo o projeto na
  # seção abaixo, ela também pode ser suprimida para uma única linha de código
  # ou um arquivo dart específico usando a sintaxe `// ignore: name_of_lint` e
  # `// ignore_for_file: name_of_lint` na linha ou no arquivo
  # que produz o lint.
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_declarations
    - sized_box_for_whitespace
    - use_key_in_widget_constructors


# Informações adicionais sobre este arquivo podem ser encontradas em
# https://dart.dev/guides/language/analysis-options
