name: conectaparana
description: "Plataforma multi-cidade para o estado do Paraná"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  dio: ^5.0.0
  
  mocktail: ^1.0.3

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/paranalogo.png"
  android_12:
    color: "#FFFFFF"
    image: "assets/images/paranalogo.png"