FROM postgres:16

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       postgis \
       postgresql-16-postgis-3 \
       postgresql-16-postgis-3-scripts \
    && rm -rf /var/lib/apt/lists/*

COPY init-postgis.sh /docker-entrypoint-initdb.d/init-postgis.sh
RUN chmod +x /docker-entrypoint-initdb.d/init-postgis.sh