export const TABLE_PREFIX = {
  USER: 'usr_',
  CITY: 'cit_',
  EVENT: 'evt_',
  POST: 'pst_',
  NEWS: 'nws_',
  LOCAL: 'loc_',
  CATEGORY: 'cat_',
  HEALTH_CHECK: 'hlt_',
  SUGGESTION: 'sgt_',
  NOTIFICATION: 'nfy_',
  LIKE: 'lke_',
  SAVE: 'sav_',
  COMMUNICATE: 'cmt_',
  PHOTO: 'pho_',
  REFRESH_TOKEN: 'rfk_',
  TICKET: 'tkt_',
  TICKET_COMMENT: 'tkc_',
} as const;
